### ISSUE TITLE
Interesting crash when using Bane Of The Dead wand.

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [elucent/Roots#62] opened 2016-07-16 11:16 UTC
forge: 2011
Minecraft: 1.10.2
roots: 0.107
This is in a modpack but it seems like its the roots mod only, from what I can tell. used the wand on a horse, froze then crash to desktop. Server was fine, this was on The New Frontier modpack
Crash:
http://pastebin.com/h9hgvWG2

**Comment by ShadowGamerXY** [comment] 2016-07-16 11:33
Are you using a mod that in any mod that changes horses, and if you have any modifiers, please tell me which one, I have been tasting but I got 0 crashes all is working as it should be.

**Comment by EPIICTHUNDERCAT** [comment] 2016-07-17 01:39
No, not that I have noticed, I attempted this on a player and got the same crash. you can log onto our server and see, I'll let you test as well of course, this is if you have time. The modpack is The New Frontier. if so, let me know add one on Curse Client and we can talk to figure it out :) @rickyvp310@gmail.com

**Comment by ShadowGamerXY** [comment] 2016-07-17 23:54
Well sorry for not answeing it is 2am here i will add you as soon as i get my sleep and i will test it

**Comment by EPIICTHUNDERCAT** [comment] 2016-07-18 05:45
yea for sure no prob, just let me know, should be 8 am for you when i post this which is 10pm for me

**Comment by werty1124** [comment] 2016-07-22 21:10
I can't reproduce this either, make sure you are using the latest version of Roots (0.109)

**Comment by EPIICTHUNDERCAT** [comment] 2016-07-22 23:11
yes this was an error happening before the new updates, havent tested 0.109

**Comment by werty1124** [comment] 2016-07-23 00:02
Closing this for now, I'll reopen if you test on 0.109 and it still happens

**Closed by werty1124** 2016-07-23 00:02 UTC
